### ISSUE TITLE
Database bootstrap fails when using Postgres Connection Pooler (e.g: PGPool II)

### ISSUE THREAD

**Issue by rblaine95** [hyperledger/aries-askar#299]
When connecting Aries Askar (tested and reproducible on `v0.3.2`) to a Postgres Database cluster via a connection pooler such as PGPool-II or AWS RDS Proxy, bootstrapping/provisioning the Database fails.

We have replicated this issue in _both_ PGPool-II _and_ AWS RDS Proxy.

_For testing and reproducing, I've been leveraging [Kubernetes in Docker (Kind)](https://kind.sigs.k8s.io)._

**How to reproduce**:
Step 1: Bring up a Postgres Cluster.
Install `bitnami/postgresql-ha`:
```yaml
# values.yaml
fullnameOverride: askar
postgresql:
  replicaCount: 1
  username: postgres
  password: postgres
  repmgrUsername: repmgr
  repmgrPassword: repmgr
  initdbScripts:
    init.sh: |-
      #!/bin/sh
      PGPASSWORD=postgres psql -v ON_ERROR_STOP=1 --username postgres --no-password --dbname postgres <<-EOSQL
        CREATE USER askar WITH PASSWORD 'askar' CREATEDB;
      EOSQL
  # https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  resourcesPreset: micro
persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenDeleted: Delete
pgpool:
  customUsers:
    usernames: askar
    passwords: askar
  adminUsername: admin
  adminPassword: admin
  # https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  resourcesPreset: micro
  tls:
    enabled: true
    autoGenerated: true
```
```sh
$ helm upgrade --install postgres \
    --version 14.2.16 \
    -f ./values.yaml \
    oci://registry-1.docker.io/bitnamicharts/postgresql-ha
```

Validate expected DBs and Roles are present:
![image](https://github.com/user-attachments/assets/baae5f59-6e42-4295-9dac-8dacd22e494f)

Step 2: Port-forward to Postgres (_not_ PGPool)
```sh
$ kubectl port-forward svc/askar-postgresql 5432
```

Step 3: Run Askar Storage `postgres::db_import` test to validate everything is working
```sh
$ POSTGRES_URL=postgres://askar:askar@localhost:5432/askar cargo test --features pg_test -- postgres::db_import
```

Validate expected `askar` Database now exists
![image](https://github.com/user-attachments/assets/8e5eef44-cc28-46a1-9ffa-aa4f5b602b16)

Step 4: Delete the `askar` Database
![image](https://github.com/user-attachments/assets/ed7ca203-9b93-490c-853a-e485eb6c2df3)

Step 5: Port-forward to PGPool
```sh
$ kubectl port-forward svc/askar-pgpool 5432
```

Step 6: Re-run the same `postgres::db_import` test and see failure:
```sh
$ POSTGRES_URL=postgres://askar:askar@localhost:5432/askar cargo test --features pg_test -- postgres::db_import
```

```
running 1 test
test postgres::db_import ... FAILED

failures:

---- postgres::db_import stdout ----
thread 'postgres::db_import' panicked at askar-storage/tests/backends.rs:439:18:
Error provisioning postgres test database: Error { kind: Backend, cause: Some(Database(PgDatabaseError { severity: Fatal, code: "XX000", message: "unable to get session context", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("pool_session_context.c"), line: Some(222), routine: None })), message: Some("Error opening database") }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    postgres::db_import

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 48 filtered out; finished in 0.15s
```
